ci:
  autofix_commit_msg: "style: auto fix by pre-commit hooks"
  autofix_prs: true
  autoupdate_branch: main
  autoupdate_schedule: quarterly
  autoupdate_commit_msg: "chore: auto update by pre-commit hooks"
repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.6.6
    hooks:
      - id: ruff
        args: [--fix, --exit-non-zero-on-fix]
        stages: [commit]
      - id: ruff-format

  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v4.0.0-alpha.8
    hooks:
      - id: prettier
        types_or: [javascript, jsx, ts, tsx, markdown, yaml, json]
        stages: [commit]
        exclude: |
          (?x)^(
              resources/resource_list.json|
              docs/memes.md
          )$
