name: Update resource_list.json & Wiki

on:
  push:
    branches:
      - "main"
    paths:
      - "meme_generator/memes/**"
  workflow_dispatch:

jobs:
  update-resource-list:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Update resource_list.json
        run: python tools/update_resource_list.py

      - name: Commit & Push changes
        uses: actions-js/push@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          message: "Update resource_list.json"
          branch: "main"

  update-wiki:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Checkout wiki repo
        uses: actions/checkout@v4
        with:
          repository: ${{ github.repository }}.wiki
          path: wiki

      - name: Setup python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Setup Poetry
        uses: Gr1N/setup-poetry@v9

      - name: Install dependencies
        run: poetry install

      - name: Install fonts
        run: |
          sudo apt install fonts-noto-color-emoji
          sudo mkdir /usr/share/fonts/myfonts
          sudo cp resources/fonts/* /usr/share/fonts/myfonts/
          fc-cache -fv

      - name: Update memes.md
        run: poetry run python wiki/update_meme_list.py

      - name: Commit & Push changes
        uses: actions-js/push@master
        with:
          directory: "wiki"
          repository: ${{ github.repository }}.wiki
          github_token: ${{ secrets.GITHUB_TOKEN }}
          message: "update meme list"
          branch: "master"
